FROM ubuntu:focal

# Use US mirrors for better reliability on GitHub Actions runners (AWS-hosted)
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://us.archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu/|http://security.ubuntu.com/ubuntu/|g' /etc/apt/sources.list && \
    echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries && \
    echo 'Acquire::http::Timeout "120";' > /etc/apt/apt.conf.d/80-timeout

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
      ca-certificates \
      curl \
      g++ \
      git \
      python3 \
      libcap-dev \
      libcap2 \
      make \
      xz-utils && \
    /usr/sbin/update-ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN mkdir /src
WORKDIR /src

COPY README.md ./
COPY Cargo.lock ./
COPY Cargo.toml ./
COPY ./src/ ./src/
COPY ./minijail/ ./minijail/
COPY Makefile ./
COPY tools/omegajail-setup ./tools/
COPY tools/omegajail-container-wrapper ./tools/
COPY tools/omegajail-cgroups-wrapper ./tools/
COPY ./policies/base/*.policy ./policies/base/
COPY ./policies/*.policy ./policies/*.frequency ./policies/

ARG OMEGAJAIL_RELEASE

ENV PATH=/root/.cargo/bin:$PATH
RUN make ECHO=echo OMEGAJAIL_RELEASE=$OMEGAJAIL_RELEASE
RUN make install
