#!/usr/bin/python3

import argparse
import glob
import hashlib
import logging
import os
import os.path
import random
import shutil
import stat
import subprocess
import sys
import tarfile
import urllib.request
from typing import Any, Dict, List, Optional, Sequence, Set, Union

import apt

_CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))


class RemoteFile:
    """Represents a file that can be downloaded from the internet"""

    def __init__(self, url: str, sha1sum: str):
        self._path = os.path.join(_CURRENT_DIR, '.remote-file-cache', sha1sum)
        if not os.path.isfile(self._path):
            logging.warning('File for %s does not exist. Downloading...', url)
            self._download(url)
            return

        m = hashlib.sha1()
        with open(self._path, 'rb') as f:
            while True:
                buf = f.read(4096)
                if not buf:
                    break
                m.update(buf)

        if m.hexdigest() != sha1sum:
            logging.warning(
                'Hash mismatch for %s. Expected %s got %s. '
                'Downloading...', url, sha1sum, m.hexdigest())
            self._download(url)

    def _download(self, url: str) -> None
        os.makedirs(os.path.dirname(self._path), exist_ok=True)
        urllib.request.urlretrieve(url, self._path)

    @property
    def path(self) -> str:
        """Returns the local path of the remote file."""
        return self._path

    def __enter__(self) -> 'RemoteFile':
        return self

    def __exit__(self, *_: Any) -> None:
        pass


class FileResolver:
    """Class that enumerates all files installed by a certain Debian package.

    Can work both recursively and non-recursively.
    """

    def __init__(self, exclude_files: Optional[Sequence[str]] = None):
        self.apt_cache = apt.Cache()
        self.files: Dict[str, Set[str]] = {}
        if exclude_files is None:
            self.exclude_files = ['/usr/share']
        else:
            self.exclude_files = list(exclude_files)

    def package_exists(self, package_name: str) -> bool:
        """Returns whether a package exists in the cache."""
        return package_name in self.apt_cache

    def files_for(self,
                  package_names: Union[str, Sequence[str]],
                  exclude_packages: Optional[Sequence[str]] = None,
                  recursive: bool = True,
                  include: Optional[Sequence[str]] = None,
                  exclude_files: Optional[Sequence[str]] = None) -> Set[str]:
        """Returns the set of files that are owned by a set of packages.

        This includes any packages (transitively, if the `recursive` flag is
        set) required by any of the packages provided.
        """
        result: Set[str] = set()
        if isinstance(package_names, str):
            package_names = [package_names]
        if not exclude_packages:
            exclude_packages = []
        for name in package_names:
            result.update(
                self.__files_for(
                    name,
                    exclude_packages=exclude_packages,
                    recursive=recursive))
        excluded: Set[str] = set()
        if include:
            for f in result:
                if not any(f.startswith(x) for x in include):
                    excluded.add(f)
        if exclude_files:
            for f in result:
                if any(f.startswith(x) for x in exclude_files):
                    excluded.add(f)
        result.symmetric_difference_update(excluded)
        return result

    def __files_for(self,
                    name: str,
                    exclude_packages: Sequence[str],
                    recursive: bool,
                    identation: int = 1) -> Set[str]:
        if name in exclude_packages:
            return set()
        if name in self.files:
            return self.files[name]
        pkg = self.apt_cache[name]
        self.files[name] = set()
        for f in pkg.installed_files:
            if not f or any(f.startswith(x) for x in self.exclude_files):
                continue
            if not os.path.exists(f):
                continue
            st = os.lstat(f)
            if stat.S_ISDIR(st.st_mode):
                continue
            self.files[name].add(f)
        if recursive and pkg.installed:
            for or_dep in pkg.installed.get_dependencies('Depends'):
                for dep in or_dep:
                    self.files[name].update(
                        self.__files_for(dep.name, exclude_packages, recursive,
                                         identation + 1))
                    break
        return self.files[name]


class Chroot:
    """Utilities to set up a chroot jail filesystem for omegajail.

    Files are hardlinked instead of copied when possible.
    """

    def __init__(self, path: str, mountpoint: str, link: bool = True):
        self.__link = link
        self.chroot = path
        self.mountpoint = mountpoint
        if not self.mountpoint.endswith('/'):
            self.mountpoint += '/'
        if os.path.exists(path):
            shutil.rmtree(path, True)
        os.makedirs(path)

    def __chroot_path(self, path: str,
                      relative_to: Optional[str] = None) -> str:
        if relative_to is None:
            root = self.mountpoint
        else:
            root = relative_to
        assert path.startswith(
            root.rstrip('/')), '%s does not start with %s' % (path, root)
        return self.chroot + path[len(root) - 1:]

    def file_exists(self, path: str,
                    relative_to: Optional[str] = None) -> bool:
        """Returns whether a file exists in the chroot."""
        return os.path.lexists(self.__chroot_path(path, relative_to))

    def mkdir(self, path: str, relative_to: Optional[str] = None) -> None:
        """Creates a directory in the chroot."""
        path = os.path.join(
            self.chroot,
            os.path.relpath(
                self.__chroot_path(path, relative_to), self.chroot))
        if os.path.isdir(path):
            return
        os.makedirs(path)

    def touch(self, path: str, relative_to: Optional[str] = None) -> None:
        """Ensures that a file exists in the chroot."""
        self.mkdir(os.path.dirname(path), relative_to)
        path = os.path.join(
            self.chroot,
            os.path.relpath(
                self.__chroot_path(path, relative_to), self.chroot))
        if os.path.isfile(path):
            return
        with open(path, 'w'):
            pass

    def copyfromhost(self,
                     path: str,
                     relative_to: Optional[str] = None,
                     exclude: Sequence[str] = ()) -> None:
        """Copies a file from the host in the same path."""
        if '*' in path:
            for p in glob.glob(path):
                self.copyfromhost(p, relative_to, exclude)
            return
        try:
            self.mkdir(os.path.dirname(path), relative_to)
        except AssertionError:
            # The roots might try to create their parent directory,
            # which will be outside the root.
            pass
        if not os.path.isdir(os.path.realpath(path)):
            self.install(path, os.path.realpath(path), relative_to)
            return
        for root, dirs, files in os.walk(path):
            if any([root.startswith(e) for e in exclude]):
                continue
            self.mkdir(root, relative_to)
            for f in files:
                filepath = os.path.join(root, f)
                if os.path.islink(filepath):
                    target = os.readlink(filepath)
                    abspath = os.path.realpath(
                        os.path.join(os.path.dirname(filepath), target))
                    if abspath.startswith(self.mountpoint):
                        self.symlink(filepath, target)
                    else:
                        try:
                            self.install(filepath, abspath, relative_to)
                        except OSError:
                            logging.exception('failed to copy %s into %s',
                                              abspath, filepath)
                else:
                    self.install(filepath, os.path.realpath(filepath),
                                 relative_to)
            for d in dirs:
                dirpath = os.path.join(root, d)
                if os.path.islink(dirpath):
                    target = os.readlink(dirpath)
                    abspath = os.path.realpath(
                        os.path.join(os.path.dirname(dirpath), target))
                    if abspath.startswith(self.mountpoint):
                        self.symlink(dirpath, target)
                    else:
                        shutil.copytree(
                            abspath, self.__chroot_path(dirpath, relative_to))

    def install(self,
                path: str,
                source: str,
                relative_to: Optional[str] = None,
                mode: Optional[int] = None) -> None:
        """Installs a file from the host using the provided path."""
        try:
            self.mkdir(os.path.dirname(path), relative_to)
            while os.path.islink(source):
                source = os.path.join(
                    os.path.dirname(source), os.readlink(source))
            if os.path.isdir(source):
                self.mkdir(path, relative_to)
            elif self.__link:
                os.link(source, self.__chroot_path(path, relative_to))
            else:
                shutil.copy(source, self.__chroot_path(path, relative_to))
            if mode is not None:
                os.chmod(self.__chroot_path(path, relative_to), mode)
        except Exception:
            logging.exception('failed to install %s into %s', source, path)
            raise

    def symlink(self, path: str, destination: str) -> None:
        """Creates a symlink in the chroot."""
        self.mkdir(os.path.dirname(path))
        try:
            os.symlink(destination, self.__chroot_path(path))
        except Exception:
            logging.exception('failed to create the symlink %s pointing to %s',
                              path, destination)
            raise

    def mknod(self, path: str, mode: int = 0o600, device: int = 0) -> None:
        """Creates a node file in the chroot."""
        self.mkdir(os.path.dirname(path))
        try:
	    os.mknod(self.__chroot_path(path), mode=mode, device=device)
            os.chmod(self.__chroot_path(path), mode & 0o777)
        except Exception:
            logging.exception('failed to mknod(%s, mode=%o, device=%d)', path,
                              mode, device)
            raise

    def write(self, path: str, contents: bytes) -> None:
        """Creates a file in the chroot with the specified contents."""
        self.mkdir(os.path.dirname(path))
        with open(self.__chroot_path(path), 'wb') as f:
            f.write(contents)
        os.utime(self.__chroot_path(path), (0, 0))

    def extract(self,
                url: str,
                sha1: str,
                skip_prefix: str = '',
                exclude: Sequence[str] = (),
                include: Optional[Sequence[str]] = None) -> None:
        """Extracts a remote file into the chroot."""
        remote_file = RemoteFile(url, sha1)
        with tarfile.open(remote_file.path) as tar:
            for member in tar.getmembers():
                path = os.path.normpath(member.name)
                if not path.startswith(skip_prefix):
                    continue
                path = self.mountpoint + path[len(skip_prefix):]
                if any([path.startswith(e) for e in exclude]):
                    continue
                if include is not None and path not in include:
                    continue
                if member.issym():
                    self.symlink(path, member.linkname)
                elif member.isfile():
                    self.mkdir(os.path.dirname(path))
                    with open(self.__chroot_path(path), 'wb') as dst:
                        shutil.copyfileobj(
                            tar.extractfile(member), dst, member.size)
                    os.chmod(self.__chroot_path(path), member.mode)

    # __enter__ and __exit__ are just provided to support with for clarity of code.
    def __enter__(self) -> 'Chroot':
        return self

    def __exit__(self, *_: Any) -> None:
        pass


def _main() -> None:
    parser = argparse.ArgumentParser(
        description='Build a chroot environment for omegajail')
    parser.add_argument(
        '--target',
        default='/var/lib/omegajail',
        help='The directory in which the chroot environment will '
        'be built')
    parser.add_argument(
        '--no-link',
        dest='link',
        action='store_false',
        help='Copy instead of linking files')
    parser.add_argument('command', nargs=argparse.REMAINDER)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    resolver = FileResolver()

    ROOT_PACKAGES = [
        'ca-certificates',
        'libc6',
        'libcap2',
        'libexpat1',
        'libffi6',
        'libgmp10',
        'libicu60',
        'liblzma5',
        'libreadline7',
        'libssl1.0.0',
        'libssl1.1',
        'libstdc++6',
        'libtinfo5',
        'libunwind8',
        'libuuid1',
        'libyaml-0-2',
        'lua5.2',
        'zlib1g',
    ]
    OPTIONAL_ROOT_PACKAGES: List[str] = []
    for package_name in OPTIONAL_ROOT_PACKAGES:
        if resolver.package_exists(package_name):
            ROOT_PACKAGES.append(package_name)

    COMPILER_PACKAGES = ROOT_PACKAGES + [
        'binutils',
        'fp-compiler',
        'fp-units-fcl-3.0.4',
        'g++',
        'gcc',
        'libbsd-dev',
        'libc6-dev',
        'libffi-dev',
        'libgmp-dev',
    ]
    OPTIONAL_COMPILER_PACKAGES = ['libitm1', 'libquadmath0', 'libtsan0']
    for package_name in OPTIONAL_COMPILER_PACKAGES:
        if resolver.package_exists(package_name):
            COMPILER_PACKAGES.append(package_name)

    RUBY_ROOT = '/usr/lib/ruby/'
    HASKELL_ROOT = '/usr/lib/ghc/'
    PYTHON2_ROOT = '/usr/lib/python2.7/'
    PYTHON3_ROOT = '/usr/lib/python3.6/'
    JAVA_ROOT = '/usr/lib/jvm/'
    DOTNET_ROOT = '/usr/share/dotnet/'
    JS_ROOT = '/opt/nodejs/'

    RUBY_FILES = resolver.files_for('ruby', exclude_packages=COMPILER_PACKAGES)
    PYTHON2_FILES = resolver.files_for('python2.7')
    PYTHON3_FILES = resolver.files_for('python3.6')
    HASKELL_FILES = resolver.files_for(
        'ghc', exclude_packages=COMPILER_PACKAGES)
    JAVA_FILES = resolver.files_for([
        'openjdk-11-jdk',
        'openjdk-11-jdk-headless',
        'openjdk-11-jre',
        'openjdk-11-jre-headless',
    ],
                                    recursive=False,
                                    exclude_files=['/etc'])
    # |resolver| excludes files from /usr/shared. All the dotnet files are in
    # that directory, so we need a new resolver that does not exclude those
    # files.
    raw_resolver = FileResolver(exclude_files=())
    DOTNET_FILES = raw_resolver.files_for([
        'dotnet-host',
        'dotnet-hostfxr-2.2',
        'dotnet-runtime-2.2',
        'dotnet-sdk-2.2',
    ],
                                          recursive=False)

    def install_common(root: Chroot) -> None:
        if not os.path.exists('/usr/lib/locale/locale-archive'):
            subprocess.check_call(
                ['/usr/sbin/locale-gen', '--purge', 'en_US.UTF-8'])
        root.copyfromhost('/usr/lib/locale/locale-archive')
        root.copyfromhost('/etc/localtime')

        root.write(
            '/etc/passwd', b'root:x:0:0:root:/:/bin/false\n'
            b'user:x:1000:1000:root:/home:/bin/false\n'
            b'nobody:x:65534:65534:nobody:/nonexistent:/bin/false')
        root.write('/etc/group', b'root:x:0:\n'
                   b'user:x:1000:\n'
                   b'nobody:x:65534:')

        # Mountpoints for libraries
        root.mkdir(RUBY_ROOT)
        root.mkdir(PYTHON2_ROOT)
        root.mkdir(PYTHON3_ROOT)
        root.mkdir(JAVA_ROOT)
        root.mkdir(HASKELL_ROOT)
        root.mkdir(DOTNET_ROOT)
        root.mkdir(JS_ROOT)

        # Other miscellaneous mountpoints
        root.mkdir('/dev/')
        root.mkdir('/proc/')
        root.mkdir('/home/')
        root.symlink('/dev/stdin', '/proc/self/fd/0')
        root.symlink('/dev/stdout', '/proc/self/fd/1')
        root.symlink('/dev/stderr', '/proc/self/fd/2')
        root.mkdir('/mnt/stdio')

        # Java wants to see which CPUs are online
        root.write('/sys/devices/system/cpu/online', b'0')

        # cgroups support
        root.mkdir('/sys/fs/cgroup/memory/omegajail')
        root.mkdir('/sys/fs/cgroup/pids/omegajail')

        # Node.js really wants a source of randomness.
        root.symlink('/dev/urandom', os.path.join(JS_ROOT, 'urandom'))

        # Device nodes
        root.mknod(
            '/dev/null', mode=0o666 | stat.S_IFCHR, device=os.makedev(1, 3))
        root.mknod(
            '/dev/zero', mode=0o666 | stat.S_IFCHR, device=os.makedev(1, 5))

        root.symlink('/usr/bin/java',
                     [x for x in JAVA_FILES if x.endswith('bin/java')][0])
        root.symlink('/usr/bin/python', os.path.join(PYTHON2_ROOT, 'python'))
        root.symlink('/usr/bin/python3', os.path.join(PYTHON3_ROOT, 'python3'))
        root.symlink('/usr/bin/node', os.path.join(JS_ROOT, 'bin/node'))
        root.symlink('/usr/lib/node_modules',
                     os.path.join(JS_ROOT, 'node_modules'))
        for f in RUBY_FILES:
            if f.startswith(RUBY_ROOT):
                continue
            root.symlink(f, os.path.join(RUBY_ROOT, f.replace('/', '_')))

    with Chroot(
            os.path.join(args.target, 'root'), '/', link=args.link) as root:
        install_common(root)

        for filename in resolver.files_for(ROOT_PACKAGES):
            root.copyfromhost(filename)

        # /tmp is an (optional) mountpoint in the normal chroot, and
        # will be left read-only for the programs that don't need it.
        root.mkdir('/tmp/')

        root.symlink('/usr/bin/lua', 'lua5.2')

    with Chroot(
            os.path.join(args.target, 'root-compilers'), '/',
            link=args.link) as root:
        install_common(root)

        for f in resolver.files_for(COMPILER_PACKAGES):
            if os.path.islink(f):
                root.symlink(f, os.readlink(f))
            else:
                root.copyfromhost(f)

        root.copyfromhost('/usr/bin/fpc')
        root.copyfromhost('/etc/fpc.cfg')
        if os.path.exists('/usr/bin/ppcarm'):
            root.copyfromhost('/usr/bin/ppcarm')
        else:
            root.copyfromhost('/usr/bin/ppcx64')
        root.symlink('/usr/bin/javac',
                     [x for x in JAVA_FILES if x.endswith('bin/javac')][0])
        for f in HASKELL_FILES:
            if f.startswith(HASKELL_ROOT):
                continue
            if root.file_exists(f):
                continue
            root.symlink(f, os.path.join(HASKELL_ROOT, f.replace('/', '_')))
        root.mkdir('/tmp/')

        root.symlink('/usr/bin/luac', 'luac5.2')

    with Chroot(
            os.path.join(args.target, 'root-openjdk'), JAVA_ROOT,
            link=args.link) as root:
        for filename in JAVA_FILES:
            root.copyfromhost(filename)

    with Chroot(
            os.path.join(args.target, 'root-python'), PYTHON_ROOT,
            link=args.link) as root:
        root.install(os.path.join(PYTHON_ROOT, 'python'), '/usr/bin/python2.7')
        for filename in PYTHON_FILES:
            if filename.startswith(PYTHON_ROOT):
                root.copyfromhost(filename)

        with RemoteFile(
                'https://raw.githubusercontent.com/omegaup/libkarel/master/libkarel.py',
                '9b67427877bb8ba5bbf3bbde9dcf828c81d3f2cd') as remote_file:
            root.install('/usr/lib/python2.7/libkarel.py', remote_file.path)

    with Chroot(
            os.path.join(args.target, 'root-python3'),
            PYTHON3_ROOT,
            link=args.link) as root:
        root.install(
            os.path.join(PYTHON3_ROOT, 'python3'), '/usr/bin/python3.6')
        for filename in PYTHON3_FILES:
            if filename.startswith(PYTHON3_ROOT):
                root.copyfromhost(filename)

        with RemoteFile(
                'https://raw.githubusercontent.com/omegaup/libkarel/master/libkarel.py',
                '9b67427877bb8ba5bbf3bbde9dcf828c81d3f2cd') as remote_file:
            root.install('/usr/lib/python3.6/libkarel.py', remote_file.path)

    with Chroot(
            os.path.join(args.target, 'root-ruby'), RUBY_ROOT,
            link=args.link) as root:
        root.install(os.path.join(RUBY_ROOT, 'ruby'), '/usr/bin/ruby')
        for filename in RUBY_FILES:
            if filename.startswith(RUBY_ROOT):
                root.copyfromhost(filename)
        for f in RUBY_FILES:
            if f.startswith(RUBY_ROOT):
                continue
            root.install(os.path.join(RUBY_ROOT, f.replace('/', '_')), f)

    with Chroot(
            os.path.join(args.target, 'root-hs'), HASKELL_ROOT,
            link=args.link) as root:
        for filename in HASKELL_FILES:
            if filename.startswith(HASKELL_ROOT):
                root.copyfromhost(filename)
        for f in HASKELL_FILES:
            if f.startswith(HASKELL_ROOT):
                continue
            root.install(os.path.join(HASKELL_ROOT, f.replace('/', '_')), f)

    with Chroot(
            os.path.join(args.target, 'root-dotnet'), DOTNET_ROOT,
            link=args.link) as root:
        for filename in DOTNET_FILES:
            if filename.startswith(DOTNET_ROOT):
                root.copyfromhost(filename)
        root.copyfromhost(
            '/usr/share/dotnet/sdk/NuGetFallbackFolder',
            relative_to=DOTNET_ROOT)
        root.write(
            os.path.join(DOTNET_ROOT, 'Main.runtimeconfig.json'),
            b'{"runtimeOptions": {'
            b'"tfm": "netcoreapp2.2", '
            b'"framework":{"name":"Microsoft.NETCore.App","version":"2.2.0"}}'
            b'}')
        root.write(
            os.path.join(DOTNET_ROOT, 'Release.rsp'),
            b'-unsafe- -checked- -nowarn:1701,1702,1705 -nostdlib- '
            b'-errorreport:none -warn:4 -define:TRACE;RELEASE;NETCOREAPP2_2 '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/mscorlib.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/netstandard.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/Microsoft.CSharp.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/Microsoft.Win32.Primitives.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.AppContext.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Buffers.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Collections.Concurrent.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Collections.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Collections.Immutable.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.ComponentModel.Annotations.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.ComponentModel.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Console.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Diagnostics.Debug.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Diagnostics.DiagnosticSource.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Diagnostics.Process.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Diagnostics.Tools.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Diagnostics.Tracing.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Dynamic.Runtime.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Globalization.Calendars.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Globalization.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Globalization.Extensions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.Compression.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.Compression.ZipFile.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.FileSystem.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.FileSystem.Primitives.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.FileSystem.Watcher.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.MemoryMappedFiles.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.IO.UnmanagedMemoryStream.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Linq.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Linq.Expressions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Linq.Parallel.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Linq.Queryable.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.Http.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.NameResolution.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.Primitives.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.Requests.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.Security.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.Sockets.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Net.WebHeaderCollection.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Numerics.Vectors.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.ObjectModel.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Reflection.DispatchProxy.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Reflection.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Reflection.Extensions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Reflection.Metadata.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Reflection.Primitives.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Reflection.TypeExtensions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Resources.Reader.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Resources.ResourceManager.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Runtime.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Runtime.Extensions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Runtime.Handles.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Runtime.InteropServices.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Runtime.InteropServices.RuntimeInformation.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Runtime.Numerics.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Security.Cryptography.Algorithms.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Security.Cryptography.Encoding.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Security.Cryptography.Primitives.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Security.Cryptography.X509Certificates.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Security.Principal.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Text.Encoding.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Text.Encoding.Extensions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Text.RegularExpressions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.Tasks.Dataflow.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.Tasks.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.Tasks.Extensions.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.Tasks.Parallel.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.Thread.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.ThreadPool.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Threading.Timer.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Xml.ReaderWriter.dll '
            b'-reference:/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Xml.XDocument.dll '
            b'-debug- -debug:embedded -filealign:512 -nologo -optimize+ '
            b'-warnaserror- -utf8output -deterministic+')

    with Chroot(os.path.join(args.target, 'root-js'), JS_ROOT) as root:
        root.extract(
            'https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz',
            '4f1bc82594d4825b79f6b93df02b5d4798b57193',
            skip_prefix='node-v12.13.1-linux-x64/',
            include=[
                os.path.join(JS_ROOT, 'LICENSE'),
                os.path.join(JS_ROOT, 'bin/node')
            ])
        with RemoteFile(
                'https://github.com/omegaup/karel.js/releases/download/v0.2.1/karel',
                '6c9e6ffb7b9ec7c4dd107974cb3fab1b531428f0') as remote_file:
            root.install(
                os.path.join(JS_ROOT, 'karel.wasm'), remote_file.path, mode=0o755)
        with RemoteFile(
                'https://github.com/omegaup/karel.js/releases/download/v0.2.1/karel.js',
                'e5aecd4a305aaaf810df6b5d038d2535fd52d857') as remote_file:
            root.install(os.path.join(JS_ROOT, 'karel.js'), remote_file.path)

        random.seed(b'\u03A9\u1F512')  # Ω🔒
        root.write(
            os.path.join(JS_ROOT, 'urandom'),
            bytes(random.randint(0, 255) for _ in range(4096)))


if __name__ == '__main__':
    _main()
