#!/bin/bash

# Performs per-boot setup of the environment needed for omegajail.
# Should be run as root.

set -e

if [[ -e /sys/fs/cgroup/cgroup.controllers ]]; then
  # Create a cgroup and make omegaup an admin.
  /bin/mkdir -p -m 0775 /sys/fs/cgroup/omegajail
  /bin/chgrp omegaup /sys/fs/cgroup/omegajail
  echo +memory > /sys/fs/cgroup/omegajail/cgroup.subtree_control
else
  # Create a memory cgroup and make omegaup an admin.
  /bin/mkdir -p -m 0775 /sys/fs/cgroup/memory/omegajail
  /bin/chgrp omegaup /sys/fs/cgroup/memory/omegajail
fi
