#!/bin/bash

# Performs setup of the omegaup cgroups needed for omegajail.
# Should be run as root.

set -e

# Make omegup the admin of the delegated memory cgroup.
if [[ ! -f /sys/fs/cgroup/cgroup.controllers ]]; then
  chown omegaup:omegaup -R /sys/fs/cgroup/memory/system.slice/omegaup-runner.service
fi
