name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@9885a4f9af674ba472de91fb3c0cb033ecb32b7e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0

      - name: Build omegajail-jammy-distrib-x86_64.tar.xz
        run: make OMEGAJAIL_RELEASE=${{ steps.bump-version.outputs.tag }} omegajail-jammy-distrib-x86_64.tar.xz

      - name: Build omegajail-jammy-rootfs-x86_64.tar.xz
        if: ${{ steps.bump-version.outputs.part == 'major' || steps.bump-version.outputs.part == 'minor' }}
        run: make omegajail-jammy-rootfs-x86_64.tar.xz

      - name: Build omegaup/omegajail-builder-rootfs-runtime container
        if: ${{ steps.bump-version.outputs.part == 'major' || steps.bump-version.outputs.part == 'minor' }}
        run: make OMEGAJAIL_RELEASE=${{ steps.bump-version.outputs.tag }} .omegajail-builder-rootfs-runtime.stamp

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.bump-version.outputs.tag }} \
            --title "${{ steps.bump-version.outputs.tag }}" \
            --generate-notes \
            ./omegajail-jammy-distrib-x86_64.tar.xz

      - name: Upload rootfs asset to release
        if: ${{ steps.bump-version.outputs.part == 'major' || steps.bump-version.outputs.part == 'minor' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.bump-version.outputs.tag }} ./omegajail-jammy-rootfs-x86_64.tar.xz

      - name: Publish omegaup/omegajail-builder-rootfs-runtime container package
        if: ${{ steps.bump-version.outputs.part == 'major' || steps.bump-version.outputs.part == 'minor' }}
        run: |
          echo "${{ github.token }}" | \
              docker login https://docker.pkg.github.com "--username=${{ github.actor }}" --password-stdin
          container_name=docker.pkg.github.com/${{ github.repository }}/omegajail-builder-rootfs-runtime:${{ steps.bump-version.outputs.tag }}
          docker tag omegaup/omegajail-builder-rootfs-runtime "${container_name}"
          docker push "${container_name}"
